name: cust-analysis
channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/districtdatalabs
dependencies:
    # Base depends
  - python
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - yellowbrick

    # Linting
  - black
  - pylint >=2.6.0
